# File: mkdocs.yml
site_name: Mathematical Analysis
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - toc.follow

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Course Notes:
    - Week 1: notes/week1.md
    - Week 2: notes/week2.md
  - Homework:
    - Assignment 1: homework/hw1.md
    - Assignment 2: homework/hw2.md
  - Resources: resources.md

# File: docs/javascripts/mathjax.js
window.MathJax = {
  tex: {
    inlineMath: [["\\(", "\\)"]],
    displayMath: [["\\[", "\\]"]],
    processEscapes: true,
    processEnvironments: true
  },
  options: {
    ignoreHtmlClass: ".*|",
    processHtmlClass: "arithmatex"
  }
};

# File: docs/index.md
# Mathematical Analysis Course

Welcome to the Mathematical Analysis course documentation. Here you'll find all course materials, homework assignments, and additional resources.

## Course Overview

This course covers fundamental concepts in mathematical analysis, including:

- Sequences and Series
- Limits and Continuity
- Differentiation
- Integration
- Convergence Tests

## Example Math Formatting

Here's how you can write math in this documentation:

Inline math: \(f(x) = x^2\) looks great!

Display math:

\[
\int_0^\infty e^{-x} dx = 1
\]

A more complex example with aligned equations:

\[
\begin{aligned}
\frac{d}{dx}e^x &= e^x \\
\frac{d}{dx}\sin(x) &= \cos(x) \\
\frac{d}{dx}\ln(x) &= \frac{1}{x}
\end{aligned}
\]

# File: docs/homework/hw1.md
# Homework 1: Sequences and Series

## Problem 1

Prove that if a sequence \((a_n)\) converges to \(L\), then the sequence \((|a_n|)\) converges to \(|L|\).

### Solution

Let's prove this step by step:

1) Given that \(\lim_{n \to \infty} a_n = L\), we need to prove that \(\lim_{n \to \infty} |a_n| = |L|\)

2) By definition of limit, for any \(\epsilon > 0\), there exists \(N \in \mathbb{N}\) such that:
   
   \[
   |a_n - L| < \epsilon \text{ for all } n \geq N
   \]

3) Using the reverse triangle inequality:
   
   \[
   \big| |a_n| - |L| \big| \leq |a_n - L|
   \]

4) Therefore, for the same \(N\):
   
   \[
   \big| |a_n| - |L| \big| \leq |a_n - L| < \epsilon \text{ for all } n \geq N
   \]

5) This proves that \(\lim_{n \to \infty} |a_n| = |L|\)

## Problem 2

Show that the sequence \(a_n = \frac{n^2 + 1}{n^2 - 1}\) converges as \(n \to \infty\).

### Solution

Let's solve this step by step:

1) First, let's try to simplify this expression:
   
   \[
   \frac{n^2 + 1}{n^2 - 1} = \frac{n^2 + 1}{n^2 - 1} \cdot \frac{1/n^2}{1/n^2} = \frac{1 + 1/n^2}{1 - 1/n^2}
   \]

2) As \(n \to \infty\), \(\frac{1}{n^2} \to 0\), therefore:
   
   \[
   \lim_{n \to \infty} a_n = \frac{1 + 0}{1 - 0} = 1
   \]
